# Building a Classfication model with neural networks

### 1. Importing Libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 

%matplotlib inline

np.random.seed(1234)

### 2. Dataset

In [3]:
m = 30

X = np.random.randint(0, 2, (2, m))
Y = np.logical_and(X[0] == 0, X[1] == 1).astype(int).reshape((1, m))

print('Training dataset X containing (x1, x2) coordinates in the columns:')
print(X)
print('Training dataset Y containing labels of two classes (0: blue, 1: red)')
print(Y)

print ('The shape of X is: ' + str(X.shape))
print ('The shape of Y is: ' + str(Y.shape))
print ('Number of training examples = ' + str(X.shape[1]))

Training dataset X containing (x1, x2) coordinates in the columns:
[[1 1 0 1 0 0 0 1 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0]
 [1 0 0 1 0 1 0 0 0 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 1 0 1 1 0]]
Training dataset Y containing labels of two classes (0: blue, 1: red)
[[0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 1 1 1 0 1 0 0 1 0]]
The shape of X is: (2, 30)
The shape of Y is: (1, 30)
Number of training examples = 30


### 2. Defining Activation Function

In [4]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

print("sigmoid(-2) = " + str(sigmoid(-2)))
print("sigmoid(0) = " + str(sigmoid(0)))
print("sigmoid(3.5) = " + str(sigmoid(3.5)))

sigmoid(-2) = 0.11920292202211755
sigmoid(0) = 0.5
sigmoid(3.5) = 0.9706877692486436


# 3.Implementing Neural Network

### 3.1 - Defining the Neural Network Structure

In [5]:
def layer_sizes(X, Y):
    """
    Args:
    X -- input dataset
    Y -- labels
    
    Returns:
    n_x -- size of input layer
    n_y -- size of output layer
    """
    
    n_x = X.shape[0]
    n_y = Y.shape[0]
    
    return (n_x, n_y)

(n_x, n_y) = layer_sizes(X, Y)
print("The size of the input layer is: n_x = " + str(n_x))
print("The size of the output layer is: n_y = " + str(n_y))

The size of the input layer is: n_x = 2
The size of the output layer is: n_y = 1


### 3.2 Initializing Model Parameters

In [6]:
def initialize_parameters(n_x, n_y):
    """
    Args:
        n_x -- size of input layer
        n_y -- size of output layer
    
    Returns:
    parameters -- python dict containing:
                        W -- weights matrix for neural network
                        b -- bias value set as vector
    """
    
    W = np.random.rand(n_y, n_x) * 0.01
    b = np.zeros((n_y, 1))
    
    parameters = {"W" : W,
                  "b" : b}
    
    return parameters

parameters = initialize_parameters(n_x, n_y)
print("W = " + str(parameters["W"]))
print("b = " + str(parameters["b"]))

W = [[0.00869127 0.00436173]]
b = [[0.]]


### 3.3 Forward Propagation And Backward Propagation

Implementing `forward_propagation()` following the equation:
\begin{align}
Z &=  W X + b,\\
A &= \sigma\left(Z\right).
\end{align}

In [7]:
def forward_propagation(X, parameters):
    """
    Args:
        X -- input data
        parameters -- python dict containing:
                        W -- weights matrix for neural network
                        b -- bias value set as vector
    Returns:
        A -- The output
    """
    W = parameters["W"]
    b = parameters["b"]
    
    # Forward Propagation to calculate Z
    Z = np.matmul(W, X) + b
    A = sigmoid(Z)
    
    return A

A = forward_propagation(X, parameters)

print("Output vector A:", A)

Output vector A: [[0.50326321 0.5021728  0.5        0.50326321 0.5        0.50109043
  0.5        0.5021728  0.5021728  0.50326321 0.50326321 0.50326321
  0.5        0.50109043 0.50326321 0.5        0.50109043 0.5
  0.50109043 0.5        0.50109043 0.50109043 0.50109043 0.50109043
  0.5021728  0.50109043 0.5021728  0.50326321 0.50109043 0.5       ]]


Computing cost using `computing_cost()` to update parameters

In [8]:
def compute_cost(A, Y):
    """
    Args:
        A -- The output of the neural network
        Y -- Orginal output values to the input
        
    Returns:
    cost -- log loss
    """
    
    m = Y.shape[1]
    
    # Computing Cost
    logprobs = - np.multiply(np.log(A), Y) - np.multiply(np.log(1 - A), 1 - Y)
    cost = 1/m * np.sum(logprobs)
    
    return cost

print("cost = " + str(compute_cost(A, Y)))

cost = 0.6946746844429882
